---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spring-petclinic
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
  template:
    metadata:
      name: spring-petclinic
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: mtajdarhussain/myspring:1.1
          ports:
            - containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic
  labels:
    app: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  ports:
    - port: 8088
      targetPort: 8080
      name: mynetwork
  type: LoadBalancer